---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      project: "gogs"
      version: "2.2.251"
      group: "io.fabric8.devops.apps"
    name: "gogs-data"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "100Mi"
    volumeName: "gogs-data"
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      project: "jenkins"
      version: "2.2.251"
      group: "io.fabric8.devops.apps"
    name: "jenkins-jobs"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "100Mi"
    volumeName: "jenkins-jobs"
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      project: "jenkins"
      version: "2.2.251"
      group: "io.fabric8.devops.apps"
    name: "jenkins-workspace"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "1Gi"
    volumeName: "jenkins-workspace"
- apiVersion: "v1"
  kind: "PersistentVolumeClaim"
  metadata:
    labels:
      provider: "fabric8"
      project: "nexus"
      version: "2.2.251"
      group: "io.fabric8.devops.apps"
    name: "nexus-storage"
  spec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: "100Mi"
    volumeName: "nexus-storage"
