apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: jenkins
  name: jenkins
  namespace: develop
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
