apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: gogs-data
    labels:
      provider: fabric8
      project: gogs
      version: 2.2.248
      group: io.fabric8.devops.apps
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    nfs:
      path: /data/gogs-data
      server: 125.222.244.21
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkins-jobs
    labels:
      provider: fabric8
      project: jenkins
      version: 2.2.248
      group: io.fabric8.devops.apps
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    nfs:
      path: /data/jenkins-jobs
      server: 125.222.244.21
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: jenkins-workspace
    labels:
      provider: fabric8
      project: jenkins
      version: 2.2.248
      group: io.fabric8.devops.apps
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    nfs:
      path: /data/jenkins-workspace
      server: 125.222.244.21
    persistentVolumeReclaimPolicy: Recycle
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: nexus-storage
    labels:
      provider: fabric8
      project: nexus
      version: 2.2.248
      group: io.fabric8.devops.apps
  spec:
    capacity:
      storage: 5Gi
    accessModes:
    - ReadWriteOnce
    nfs:
      path: /data/nexus-storage
      server: 125.222.244.21
    persistentVolumeReclaimPolicy: Recycle
