apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  name: postgresql
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
status: {}
